schema = {
    "type": "object",
    "properties": {
        "chain": {"type": "integer"},
        "block_number": {"type": "string"},
        "hash": {"type": "string"},
        "parent_hash": {"type": "string"},
        "uncles_hash": {"type": "string"},
        "miner": {"type": "string"},
        "state_root": {"type": "string"},
        "transactions_root": {"type": "string"},
        "receipts_root": {"type": "string"},
        "gas_used": {"type": "string"},
        "gas_limit": {"type": "string"},
        "base_fee_per_gas": {"type": "string"},
        "extra_data": {"type": "string"},
        "logs_bloom": {"type": "string"},
        "timestamp": {"type": "integer"},
        "difficulty": {"type": "string"},
        "total_difficulty": {"type": "string"},
        "size": {"type": "string"},
        "mix_hash": {"type": "string"},
        "nonce": {"type": "string"},
    },
    "required": [
        "chain",
        "block_number",
        "hash",
        "parent_hash",
        "uncles_hash",
        "miner",
        "state_root",
        "transactions_root",
        "receipts_root",
        "gas_used",
        "gas_limit",
        "base_fee_per_gas",
        "extra_data",
        "logs_bloom",
        "timestamp",
        "difficulty",
        "total_difficulty",
        "size",
        "mix_hash",
        "nonce",
    ],
}
